version: "3"
services:  
  auth0demo:    
    image: ilovelili/auth0demo:woodstock
    ports:
    - "3000:3000"
    environment:        
    - AUTH0_DOMAIN=woodstock.jp.auth0.com    
    - AUTH0_BASE_URL=http://localhost:3000
    - AUTH0_CALLBACK_URL=http://localhost:3000/callback
    restart: always
